
name: HTML/CSS Check
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
​
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
​
      - name: Validate file structure
        run: |
          echo "Checking for index.html..."
          test -f index.html || (echo "Error: No index html file found" && exit 1)
​
          echo "Checking for styles folder..."
          test -d css || test -d styles || (echo "Error: No folder for CSS files found" && exit 1)
Collapse



